### ISSUE TITLE
Detected blocking call

### ISSUE THREAD

**Issue by EchoPouet** [gduteil/cozytouch#19]
Hello,

I have an error with your component.
I use HA Core version 2024.10.2.

The issue log is as follow:
```
2024-10-14 18:45:43.423 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/Cozytouch.json', 'w') inside the event loop by custom integration 'cozytouch' at custom_components/cozytouch/hub.py, line 187: with open( (offender: /config/custom_components/cozytouch/hub.py, line 187: with open(), please create a bug report at https://github.com/gduteil/cozytouch/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/cozytouch/__init__.py", line 44, in async_setup_entry
    await theHub.connect()
  File "/config/custom_components/cozytouch/hub.py", line 160, in connect
    self.update_devices_from_json_data(json_data)
  File "/config/custom_components/cozytouch/hub.py", line 187, in update_devices_from_json_data
    with open(
```

The issue appear when I reboot my HA box.

**Comment by gduteil** [comment]
Thank you for reporting, I just checked and I have the same error after one of the latest HA updates, I'll check it and let you know?
